2018-10-24 12:14:11 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: urpspider)
2018-10-24 12:14:11 [scrapy.utils.log] INFO: Versions: lxml 4.2.1.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.16299-SP0
2018-10-24 12:14:11 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'urpspider', 'CONCURRENT_REQUESTS_PER_IP': 1, 'DOWNLOAD_DELAY': 3, 'DOWNLOAD_TIMEOUT': 100, 'FEED_EXPORT_ENCODING': 'gb18030', 'LOG_FILE': 'logs\\urpspider\\urplogin\\3da44bacd74311e8862ac83dd48af256.log', 'NEWSPIDER_MODULE': 'urpspider.spiders', 'ROBOTSTXT_OBEY': True, 'SPIDER_MODULES': ['urpspider.spiders']}
2018-10-24 12:14:11 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-24 12:14:11 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-24 12:14:11 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "e:\pythonprogram\venv\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "e:\pythonprogram\venv\lib\site-packages\scrapy\crawler.py", line 79, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "e:\pythonprogram\venv\lib\site-packages\scrapy\crawler.py", line 102, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "e:\pythonprogram\venv\lib\site-packages\scrapy\spiders\__init__.py", line 51, in from_crawler
    spider = cls(*args, **kwargs)
  File "c:\users\12498\appdata\local\temp\urpspider-1540354310-0fdjsmxu.egg\urpspider\spiders\urplogin.py", line 17, in __init__
  File "C:\Program Files\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
